---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: source-code-volume
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 30Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epics-dev-container
spec:
  selector:
    matchLabels:
      app: epics-dev-container
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
                { 
                "name": "sdf-ad-ingest",
                "namespace": "multus-system" 
                }
          ]'
      labels:
        app: epics-dev-container
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: edu.stanford.slac.sdf.k8s.networking.multus
                operator: In
                values:
                - enable
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/ext-load-balancer
      containers:
      - name: epics-dev-container
        image: ghcr.io/epics-containers/epics-base-runtime:7.0.8ad3
        imagePullPolicy: Always
        command: [sleep]
        args: ['infinity']
        envFrom:
        - configMapRef:
            name: epics-env-config
        # volumeMounts:
        # - name: source-code-volume
        #   mountPath: /sources
        resources:
          limits:
            memory: 8Gi
            cpu: 4000m
      # volumes:
      # - name: source-code-volume
      #   persistentVolumeClaim:
      #     claimName: source-code-volume