apiVersion: apps/v1
kind: Deployment
metadata:
  name: epics-dev-container
spec:
  selector:
    matchLabels:
      app: epics-dev-container
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
      labels:
        app: epics-dev-container
    spec:
      containers:
      - name: epics-dev-container
        image: ghcr.io/epics-containers/epics-base-linux-developer:23.3.1
        imagePullPolicy: Always
        command: [sleep]
        args: ['infinity']
        envFrom:
        - configMapRef:
            name: epics-env-config
        resources:
          limits:
            memory: 512Mi
            cpu: 1000m