apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: gh-secret
spec:
  path: secret/lcls/lcls-k2eg/gh-secret
  type: kubernetes.io/dockerconfigjson
  keys:
    - username
    - password
  templates:
    ".dockerconfigjson": |
      {"auths": {"ghcr.io":{"username":"{% .Secrets.username %}","password":"{% .Secrets.password %}","auth":"{% list .Secrets.username ":" .Secrets.password | join "" | b64enc %}"}}}  