apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: lcls-k2eg-cmd-topic-debug
  labels:
    strimzi.io/cluster: lcls-cluster
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824