apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka

resources:
- operator.yaml
- cluster.yaml
- k2eg-single-node.yaml

secretGenerator:
  - name: ghcr-io-secret
    literals:
      - .dockerconfigjson=<to use vault>
    type: "kubernetes.io/dockerconfigjson"