apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka

resources:
- operator.yaml
- cluster.yaml
- k2eg-single-node.yaml
- gh-secret.yaml

configMapGenerator:
- name: epics-env-config
  envs:
  - epics.env
generatorOptions:
  disableNameSuffixHash: true # use a static name